# Generated by Django 6.0.8 on 2026-10-01 00:25

from django.db import migrations, models


def unobserve_public_access(apps, schema_editor):
    """Every stored ``public_access_blocked`` before this migration is the old model default
    (True): the collector never projected the field, so no row holds an observation. Clear them to
    null (not observed, req-aws-core-fields-8) rather than leave every bucket reading "blocked";
    the next collection fills the field from GetPublicAccessBlock (req-aws-core-fields-9)."""
    S3Bucket = apps.get_model("aws_core", "S3Bucket")
    S3Bucket.objects.update(public_access_blocked=None)


class Migration(migrations.Migration):

    dependencies = [
        ('aws_core', '0013_regional_containment'),
        ('tap_grid', '0005_entity_natural_key_clear'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cloudwatchloggroup',
            name='nk_aws_core__aws_cloud_c8fed67',
        ),
        migrations.AlterField(
            model_name='historicals3bucket',
            name='public_access_blocked',
            field=models.BooleanField(blank=True, default=None, help_text='Bucket-level S3 Block Public Access: true when all four flags are on, false when any is off or none is configured, null when not observed. Account-level Block Public Access is not modelled.', null=True),
        ),
        migrations.AlterField(
            model_name='s3bucket',
            name='public_access_blocked',
            field=models.BooleanField(blank=True, default=None, help_text='Bucket-level S3 Block Public Access: true when all four flags are on, false when any is off or none is configured, null when not observed. Account-level Block Public Access is not modelled.', null=True),
        ),
        migrations.RunPython(unobserve_public_access, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='cloudwatchloggroup',
            index=models.Index(fields=['log_group_arn'], name='nk_aws_core__aws_cloud_c8fed67'),
        ),
    ]
