# Generated by Django 6.0.8 on 2026-10-01 18:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0014_s3_public_access_observed_and_log_group_arn_key"),
        ("tap_grid", "0005_entity_natural_key_clear"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="awsorganization",
            name="enabled_policy_types",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsorganization",
            name="enabled_service_principals",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsorganization",
            name="tags",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsorganization",
            name="enabled_policy_types",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsorganization",
            name="enabled_service_principals",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsorganization",
            name="tags",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name="AwsOrganizationsPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "policy_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                ("policy_id", models.CharField(blank=True, default="", max_length=130)),
                (
                    "policy_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "aws_managed",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_organizations_policy",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalAwsDelegatedAdministration",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "organization_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("account_id", models.CharField(blank=True, default="", max_length=12)),
                (
                    "service_principal",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "delegation_enabled_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws delegated administration",
                "verbose_name_plural": "historical aws delegated administrations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsOrganizationsPolicy",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "policy_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                ("policy_id", models.CharField(blank=True, default="", max_length=130)),
                (
                    "policy_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "aws_managed",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws organizations policy",
                "verbose_name_plural": "historical aws organizations policys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsPolicyStatement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "policy_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "statement_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("sid", models.CharField(blank=True, default="", max_length=255)),
                ("effect", models.CharField(blank=True, default="", max_length=8)),
                ("actions", models.JSONField(blank=True, default=None, null=True)),
                ("not_actions", models.JSONField(blank=True, default=None, null=True)),
                ("resources", models.JSONField(blank=True, default=None, null=True)),
                (
                    "not_resources",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("principals", models.JSONField(blank=True, default=None, null=True)),
                (
                    "not_principals",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("conditions", models.JSONField(blank=True, default=None, null=True)),
                ("positions", models.JSONField(blank=True, default=None, null=True)),
                (
                    "occurrences",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "content_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws policy statement",
                "verbose_name_plural": "historical aws policy statements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsTagPolicyRule",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "policy_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "tag_key_lower",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("tag_key", models.CharField(blank=True, default="", max_length=128)),
                (
                    "allowed_values",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("enforced_for", models.JSONField(blank=True, default=None, null=True)),
                (
                    "inheritance_operators",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws tag policy rule",
                "verbose_name_plural": "historical aws tag policy rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AwsDelegatedAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "organization_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("account_id", models.CharField(blank=True, default="", max_length=12)),
                (
                    "service_principal",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "delegation_enabled_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_delegated_administration",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization_id", "account_id", "service_principal"],
                        name="nk_aws_core__aws_deleg_c0dbfda",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AwsPolicyStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "policy_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "statement_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("sid", models.CharField(blank=True, default="", max_length=255)),
                ("effect", models.CharField(blank=True, default="", max_length=8)),
                ("actions", models.JSONField(blank=True, default=None, null=True)),
                ("not_actions", models.JSONField(blank=True, default=None, null=True)),
                ("resources", models.JSONField(blank=True, default=None, null=True)),
                (
                    "not_resources",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("principals", models.JSONField(blank=True, default=None, null=True)),
                (
                    "not_principals",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("conditions", models.JSONField(blank=True, default=None, null=True)),
                ("positions", models.JSONField(blank=True, default=None, null=True)),
                (
                    "occurrences",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "content_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_policy_statement",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["policy_arn", "statement_key"],
                        name="nk_aws_core__aws_polic_e2c056b",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AwsTagPolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "policy_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "tag_key_lower",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("tag_key", models.CharField(blank=True, default="", max_length=128)),
                (
                    "allowed_values",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("enforced_for", models.JSONField(blank=True, default=None, null=True)),
                (
                    "inheritance_operators",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_tag_policy_rule",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["policy_arn", "tag_key_lower"],
                        name="nk_aws_core__aws_tag_p_193a7e2",
                    )
                ],
            },
        ),
    ]
