# Generated by Django 6.0.8 on 2026-10-01 22:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0015_organizations_completeness"),
        ("tap_grid", "0005_entity_natural_key_clear"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="awsaccount",
            name="s3_block_public_acls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="s3_block_public_policy",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="s3_ignore_public_acls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="s3_restrict_public_buckets",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsaccountregion",
            name="ebs_default_kms_key_id",
            field=models.CharField(
                blank=True, default=None, max_length=2048, null=True
            ),
        ),
        migrations.AddField(
            model_name="awsaccountregion",
            name="ebs_encryption_by_default",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsidentitycenterinstance",
            name="regions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsidentitycenterinstance",
            name="status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="historicalawsaccount",
            name="s3_block_public_acls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsaccount",
            name="s3_block_public_policy",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsaccount",
            name="s3_ignore_public_acls",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsaccount",
            name="s3_restrict_public_buckets",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsaccountregion",
            name="ebs_default_kms_key_id",
            field=models.CharField(
                blank=True, default=None, max_length=2048, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalawsaccountregion",
            name="ebs_encryption_by_default",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsidentitycenterinstance",
            name="regions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsidentitycenterinstance",
            name="status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.CreateModel(
            name="AwsAccessAnalyzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "analyzer_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "analyzer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "analyzer_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_access_analyzer",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsConfigAggregator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "aggregator_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "aggregator_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("organization_wide", models.BooleanField(default=False)),
                ("source_account_ids", models.JSONField(blank=True, default=list)),
                (
                    "all_aws_regions",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("aws_regions", models.JSONField(blank=True, default=list)),
                ("role_arn", models.CharField(blank=True, default="", max_length=2048)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_config_aggregator",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsConfigRecorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "recorder_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "recorder_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("recording", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "last_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "service_principal",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "recording_scope",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("role_arn", models.CharField(blank=True, default="", max_length=2048)),
                (
                    "all_supported",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "include_global_resource_types",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_config_recorder",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsControlTowerEnabledBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "enabled_baseline_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "baseline_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "baseline_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "parent_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "drift_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_controltower_enabled_baseline",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsControlTowerEnabledControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "enabled_control_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "control_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "target_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "parent_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "drift_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_controltower_enabled_control",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsControlTowerLandingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "landing_zone_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "home_region",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("version", models.CharField(blank=True, default="", max_length=32)),
                (
                    "latest_available_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "drift_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "governed_regions",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_controltower_landing_zone",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsIdentityCenterPermissionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "permission_set_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1224
                    ),
                ),
                (
                    "instance_arn",
                    models.CharField(blank=True, default="", max_length=1224),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=700),
                ),
                (
                    "session_duration",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "relay_state",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                (
                    "managed_policy_arns",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_identity_center_permission_set",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsSecurityHubHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "subscribed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "auto_enable_controls",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "control_finding_generator",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "enabled_standards",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "administrator_account_id",
                    models.CharField(
                        blank=True, default=None, max_length=12, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_securityhub_hub",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalAwsAccessAnalyzer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "analyzer_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "analyzer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "analyzer_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws access analyzer",
                "verbose_name_plural": "historical aws access analyzers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsConfigAggregator",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "aggregator_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "aggregator_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("organization_wide", models.BooleanField(default=False)),
                ("source_account_ids", models.JSONField(blank=True, default=list)),
                (
                    "all_aws_regions",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("aws_regions", models.JSONField(blank=True, default=list)),
                ("role_arn", models.CharField(blank=True, default="", max_length=2048)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws config aggregator",
                "verbose_name_plural": "historical aws config aggregators",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsConfigDeliveryChannel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "account_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                (
                    "channel_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "s3_bucket_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "s3_key_prefix",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "s3_kms_key_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "sns_topic_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "delivery_frequency",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws config delivery channel",
                "verbose_name_plural": "historical aws config delivery channels",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsConfigRecorder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "recorder_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "recorder_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("recording", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "last_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "service_principal",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "recording_scope",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("role_arn", models.CharField(blank=True, default="", max_length=2048)),
                (
                    "all_supported",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "include_global_resource_types",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws config recorder",
                "verbose_name_plural": "historical aws config recorders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsControlTowerEnabledBaseline",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "enabled_baseline_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "baseline_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "baseline_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "parent_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "drift_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws control tower enabled baseline",
                "verbose_name_plural": "historical aws control tower enabled baselines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsControlTowerEnabledControl",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "enabled_control_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "control_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "target_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "parent_identifier",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "drift_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws control tower enabled control",
                "verbose_name_plural": "historical aws control tower enabled controls",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsControlTowerLandingZone",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "landing_zone_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "home_region",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("version", models.CharField(blank=True, default="", max_length=32)),
                (
                    "latest_available_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "drift_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "governed_regions",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws control tower landing zone",
                "verbose_name_plural": "historical aws control tower landing zones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsGuardDutyDetector",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "account_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                (
                    "detector_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=300
                    ),
                ),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                (
                    "finding_publishing_frequency",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "administrator_account_id",
                    models.CharField(
                        blank=True, default=None, max_length=12, null=True
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws guard duty detector",
                "verbose_name_plural": "historical aws guard duty detectors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsIdentityCenterAccountAssignment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "instance_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1224
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                (
                    "permission_set_arn",
                    models.CharField(blank=True, default="", max_length=1224),
                ),
                (
                    "principal_type",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "principal_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws identity center account assignment",
                "verbose_name_plural": "historical aws identity center account assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsIdentityCenterGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "identity_store_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("external_ids", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws identity center group",
                "verbose_name_plural": "historical aws identity center groups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsIdentityCenterPermissionSet",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "permission_set_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1224
                    ),
                ),
                (
                    "instance_arn",
                    models.CharField(blank=True, default="", max_length=1224),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=700),
                ),
                (
                    "session_duration",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "relay_state",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                (
                    "managed_policy_arns",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws identity center permission set",
                "verbose_name_plural": "historical aws identity center permission sets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsSecurityHubHub",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hub_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "subscribed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "auto_enable_controls",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "control_finding_generator",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "enabled_standards",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "administrator_account_id",
                    models.CharField(
                        blank=True, default=None, max_length=12, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws security hub hub",
                "verbose_name_plural": "historical aws security hub hubs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AwsConfigDeliveryChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "account_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                (
                    "channel_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "s3_bucket_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "s3_key_prefix",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "s3_kms_key_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "sns_topic_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "delivery_frequency",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_config_delivery_channel",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["account_id", "region", "channel_name"],
                        name="nk_aws_core__aws_confi_b6e9cc6",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AwsGuardDutyDetector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "account_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                (
                    "detector_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=300
                    ),
                ),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                (
                    "finding_publishing_frequency",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "administrator_account_id",
                    models.CharField(
                        blank=True, default=None, max_length=12, null=True
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_guardduty_detector",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["account_id", "region", "detector_id"],
                        name="nk_aws_core__aws_guard_18e4804",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AwsIdentityCenterAccountAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "instance_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1224
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                (
                    "permission_set_arn",
                    models.CharField(blank=True, default="", max_length=1224),
                ),
                (
                    "principal_type",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "principal_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_identity_center_account_assignment",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=[
                            "instance_arn",
                            "account_id",
                            "permission_set_arn",
                            "principal_type",
                            "principal_id",
                        ],
                        name="nk_aws_core__aws_ident_53bf25e",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AwsIdentityCenterGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "identity_store_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("external_ids", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_identity_center_group",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["identity_store_id", "group_id"],
                        name="nk_aws_core__aws_ident_c27aa83",
                    )
                ],
            },
        ),
    ]
