# Generated by Django 6.0.8 on 2026-10-02 13:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0016_landing_zone_governance"),
        ("tap_grid", "0005_entity_natural_key_clear"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="awsaccessanalyzer",
            name="active_finding_counts",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsaccessanalyzer",
            name="active_finding_counts_complete",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsaccessanalyzer",
            name="active_findings_truncated",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsguarddutydetector",
            name="active_finding_counts",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsguarddutydetector",
            name="active_finding_counts_complete",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awsguarddutydetector",
            name="active_findings_truncated",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awssecurityhubhub",
            name="active_finding_counts",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awssecurityhubhub",
            name="active_finding_counts_complete",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="awssecurityhubhub",
            name="active_findings_truncated",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsaccessanalyzer",
            name="active_finding_counts",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsaccessanalyzer",
            name="active_finding_counts_complete",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsaccessanalyzer",
            name="active_findings_truncated",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsguarddutydetector",
            name="active_finding_counts",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsguarddutydetector",
            name="active_finding_counts_complete",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawsguarddutydetector",
            name="active_findings_truncated",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawssecurityhubhub",
            name="active_finding_counts",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawssecurityhubhub",
            name="active_finding_counts_complete",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalawssecurityhubhub",
            name="active_findings_truncated",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="AwsConfigConformancePack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "pack_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                ("pack_name", models.CharField(blank=True, default="", max_length=256)),
                ("pack_id", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "delivery_s3_bucket",
                    models.CharField(blank=True, default="", max_length=63),
                ),
                (
                    "last_update_requested_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_config_conformance_pack",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsConfigRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "rule_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                ("rule_name", models.CharField(blank=True, default="", max_length=128)),
                ("rule_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "source_owner",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "source_identifier",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("state", models.CharField(blank=True, default="", max_length=32)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "maximum_execution_frequency",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "non_compliant_resource_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "non_compliant_count_capped",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_config_rule",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsGuardDutyFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "finding_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "finding_id",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "detector_id",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("account_id", models.CharField(blank=True, default="", max_length=12)),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                (
                    "finding_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("severity", models.FloatField(blank=True, default=None, null=True)),
                (
                    "severity_label",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("first_seen", models.CharField(blank=True, default="", max_length=40)),
                ("last_seen", models.CharField(blank=True, default="", max_length=40)),
                ("count", models.IntegerField(blank=True, default=None, null=True)),
                ("archived", models.BooleanField(blank=True, default=None, null=True)),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("updated_at", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_guardduty_finding",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AwsSecurityHubStandardsSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subscription_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "standards_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "standards_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                (
                    "status_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "controls_updatable",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_securityhub_standards_subscription",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalAwsAccessAnalyzerFinding",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "finding_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "analyzer_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "resource_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "resource_owner_account",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                (
                    "finding_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                ("is_public", models.BooleanField(blank=True, default=None, null=True)),
                ("principal", models.JSONField(blank=True, default=None, null=True)),
                ("actions", models.JSONField(blank=True, default=None, null=True)),
                (
                    "condition_keys",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("updated_at", models.CharField(blank=True, default="", max_length=40)),
                (
                    "analyzed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws access analyzer finding",
                "verbose_name_plural": "historical aws access analyzer findings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsConfigConformancePack",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "pack_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                ("pack_name", models.CharField(blank=True, default="", max_length=256)),
                ("pack_id", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "delivery_s3_bucket",
                    models.CharField(blank=True, default="", max_length=63),
                ),
                (
                    "last_update_requested_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws config conformance pack",
                "verbose_name_plural": "historical aws config conformance packs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsConfigRule",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "rule_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                ("rule_name", models.CharField(blank=True, default="", max_length=128)),
                ("rule_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "source_owner",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "source_identifier",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("state", models.CharField(blank=True, default="", max_length=32)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "maximum_execution_frequency",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "non_compliant_resource_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "non_compliant_count_capped",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws config rule",
                "verbose_name_plural": "historical aws config rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsGuardDutyFinding",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "finding_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "finding_id",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "detector_id",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("account_id", models.CharField(blank=True, default="", max_length=12)),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                (
                    "finding_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("severity", models.FloatField(blank=True, default=None, null=True)),
                (
                    "severity_label",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("first_seen", models.CharField(blank=True, default="", max_length=40)),
                ("last_seen", models.CharField(blank=True, default="", max_length=40)),
                ("count", models.IntegerField(blank=True, default=None, null=True)),
                ("archived", models.BooleanField(blank=True, default=None, null=True)),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("updated_at", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws guard duty finding",
                "verbose_name_plural": "historical aws guard duty findings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsSecurityHubFinding",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "finding_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "product_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "generator_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "aws_account_id",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "severity_label",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "workflow_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "record_state",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "compliance_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "security_control_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("associated_standards", models.JSONField(blank=True, default=list)),
                ("resource_types", models.JSONField(blank=True, default=list)),
                ("resource_ids", models.JSONField(blank=True, default=list)),
                (
                    "first_observed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "last_observed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("updated_at", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws security hub finding",
                "verbose_name_plural": "historical aws security hub findings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAwsSecurityHubStandardsSubscription",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subscription_arn",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2048
                    ),
                ),
                (
                    "standards_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "standards_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                (
                    "status_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "controls_updatable",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aws security hub standards subscription",
                "verbose_name_plural": "historical aws security hub standards subscriptions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AwsAccessAnalyzerFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "finding_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "analyzer_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "resource_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "resource_owner_account",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                (
                    "finding_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("status", models.CharField(blank=True, default="", max_length=16)),
                ("is_public", models.BooleanField(blank=True, default=None, null=True)),
                ("principal", models.JSONField(blank=True, default=None, null=True)),
                ("actions", models.JSONField(blank=True, default=None, null=True)),
                (
                    "condition_keys",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("updated_at", models.CharField(blank=True, default="", max_length=40)),
                (
                    "analyzed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_access_analyzer_finding",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["analyzer_arn", "finding_id"],
                        name="nk_aws_core__aws_acces_b983a02",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AwsSecurityHubFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "finding_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "product_arn",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "generator_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "aws_account_id",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("region", models.CharField(blank=True, default="", max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "severity_label",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "workflow_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "record_state",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "compliance_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "security_control_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("associated_standards", models.JSONField(blank=True, default=list)),
                ("resource_types", models.JSONField(blank=True, default=list)),
                ("resource_ids", models.JSONField(blank=True, default=list)),
                (
                    "first_observed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "last_observed_at",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created_at", models.CharField(blank=True, default="", max_length=40)),
                ("updated_at", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "aws_core__aws_securityhub_finding",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["product_arn", "finding_id"],
                        name="nk_aws_core__aws_secur_e861e8b",
                    )
                ],
            },
        ),
    ]
